### ISSUE TITLE
Use coder_{metadata, app} to expose kubeconfig

### ISSUE THREAD

**Issue by hh** [sharingio/coder#11]
- Use coder_metadata for kubeconfig
Will need to wait until kubeconfig is available to have a terraform kubernetes_resource output to reference in a coder_metadata.

- Use coder_app to expose tmux or similar
Will need a tty command to attach and possible a second coder_app to expose the web ui.

**Comment by hh** [comment]
Try this, it's a single go binary, run it within the pod: https://github.com/tsl0922/ttyd

**Comment by hh** [comment]
`
sudo apt-get install build-essential cmake git libjson-c-dev libwebsockets-dev
git clone https://github.com/tsl0922/ttyd.git
cd ttyd && mkdir build && cd build
cmake ..
make && sudo make install

**Comment by hh** [comment]
- https://github.com/yudai/gotty

**Comment by hh** [comment]
Three ways to connect:
- coder_app with command (click to connect via web)
- coder_app with http://localhost:3838 for goTTY
- coder ssh WS tmux attach
- coder ssh to tty command

**Comment by BobyMCbobs** [comment]
GoTTY appears to be five years unmaintained

<img width="708" alt="image" src="https://user-images.githubusercontent.com/8588826/196800488-90ef5ec2-03ad-49c3-9c34-94c95b2bec6d.png">
<img width="872" alt="image" src="https://user-images.githubusercontent.com/8588826/196800534-61ee84d1-0d75-4fc4-972e-cad67e09c4d9.png">
<img width="621" alt="image" src="https://user-images.githubusercontent.com/8588826/196800570-94335c76-f730-47e5-b5e8-2d1fc20324cb.png">

**Comment by hh** [comment]
ttyd looks pretty active:
https://github.com/tsl0922/ttyd/graphs/contributors

**Comment by BobyMCbobs** [comment]
Can't seem to find ttyd x86_64 / amd64 prebuilds
https://github.com/tsl0922/ttyd/releases/tag/1.7.2

**Comment by hh** [comment]
On pair:
```
curl -LO https://github.com/tsl0922/ttyd/releases/download/1.7.2/ttyd.x86_64
chmod +x ttyd.x86_64
./ttyd.x86_64 --version
ttyd version 1.7.2-020e2f3 
```

**Comment by BobyMCbobs** [comment]
> On pair:
> 
> ```
> curl -LO https://github.com/tsl0922/ttyd/releases/download/1.7.2/ttyd.x86_64
> chmod +x ttyd.x86_64
> ./ttyd.x86_64 --version
> ttyd version 1.7.2-020e2f3 
> ```

Seems it was the last in the list. Missed that one. Thank you!

**Comment by sbdtu5498** [comment]
@BobyMCbobs please do not bother yourself with this issue. I am working on it.

**Comment by hh** [comment]
ttyd is working now. Let's swing back around to coder_app "kubeconfig"

**Comment by hh** [comment]
https://jamesdefabia.github.io/docs/user-guide/kubectl/kubectl_config_set-cluster/

> --insecure-skip-tls-verify=true

**Comment by hh** [comment]
The kubeconfig itself should be able to be populated via `coder_metadata`:

https://coder.com/docs/coder-oss/latest/secrets#displaying-secrets

**Comment by BobyMCbobs** [comment]
> The kubeconfig itself should be able to be populated via `coder_metadata`:
> 
> https://coder.com/docs/coder-oss/latest/secrets#displaying-secrets

The problem we have been having to prevent this from being easy is due to how Terraform works.
`data` will fetch the resource at the start and will not wait for the target resource to be created.
This means that we will need to jump through hoops if to expose the kubeconfig at all.

Currently winding up with the following error
```
  data.kubernetes_secret_v1.kubeconfig: Refreshing...
  data.kubernetes_secret_v1.kubeconfig: Refresh complete after 0s
  Error: Attempt to get attribute from null value
  This value is null, so it does not have any attributes.
```

**Comment by BobyMCbobs** [comment]
Managed to get it working through a sleep in
https://github.com/sharingio/coder/commit/48a5757e8c327b28764a817623693aa0049db999
and it shows up in the UI under namespace

The success should be taken lightly though, considering that sleep can make things flakey.
