### ISSUE TITLE
Manifest a Management Cluster : Equinix based similar to pair management cluster

### ISSUE THREAD

**Issue by hh** [sharingio/coder#14]
This will be written as a manifest or similar creating a management cluster similar to pair:

- [x] Firstly it should deploy clusters similarly to our pair go code
- [ ] It may pull in manifests and parts of the pair helm chart
- [x] Lilkely a cluster-api-packet deployment of the above
- [ ] Should then include the sharingio/coder/.sharingio/init manifest etc we currently use the run coder on pair
- [x] DNS should work similarly to they way it does on the pair management cluster

**Comment by BobyMCbobs** [comment]
Currently setting up a cluster as is defined in
https://github.com/cncf-infra/coder-infra
The _cloud-provider-equinix-metal_ controller isn't starting although it's priority class is _system-role-critical_

**Comment by hh** [comment]
Still not starting?

**Comment by BobyMCbobs** [comment]
> Still not starting?

This issue is still occurring. I'm working on it

**Comment by BobyMCbobs** [comment]
There's an auto-import for the kubernetes template, when using the Helm chart
https://github.com/coder/coder/pull/3550
It appears to only support the kubernetes template.

Unsure how it pulls it in

**Comment by BobyMCbobs** [comment]
What domain will the Coder server run on?

**Comment by hh** [comment]
I think it's fine to have it be a terraform variable or similar input.

It should configure the NS entries over at dnsimple using an api key.

For now you can use coder.sharing.io

**Comment by BobyMCbobs** [comment]
Thank you for your response @hh 

Terraform over-complicates it at this point, so just doing plain or envsubst'd yaml.

Gonna bring up with PowerDNS, since this has been previously discussed.
Supported DNS01 providers
https://cert-manager.io/docs/configuration/acme/dns01/#supported-dns01-providers
We'd wanna use
[RFC2136](https://cert-manager.io/docs/configuration/acme/dns01/rfc2136/)
with PowerDNS
(or Route53)

I'll be bringing it up on https://coder.sharing.io then.

**Comment by hh** [comment]
I like it!

**Comment by BobyMCbobs** [comment]
progress
https://github.com/cncf-infra/coder-infra/issues/1

**Comment by BobyMCbobs** [comment]
Managed to get a cluster up using _cluster-api-provider-packet_ with 
- cilium
- cluster-api
- cert-manager
- external-dns
- ingress-nginx
- kubevirt
- longhorn
- metallb
- powerdns
- stackgres
- Coder

Currently there's issue for Coder to talk to the Postgres cluster. Trying to figure that out. Have also reached out to the Coder folks
