### ISSUE TITLE
GitHub Cloud Native CodeSpaces

### ISSUE THREAD

**Issue by hh** [sharingio/coder#7]
Create a [custom](https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/introduction-to-dev-containers#creating-a-custom-dev-container-configuration
) [dev container](https://containers.dev) that brings up kind, and explore if it's possible to connect the VSCode environment shells / target to use a pod within that cluster.

Some longer term goals that this is exploring the possibility of:
- can we change the environment of VSCode+codespaces to target the cluster+pod?
- what hooks do we have to handle ingress?
- could we change the underlying VM provider to be a hosted Kubernetes or other cloud provider (VM+Kind, AKS, EKS, GKE)

Background:
I met with @craiglpeters while in SF and we talked about the starting points for getting VSCode to target k8s clusters when brought up in workspaces. He's given our team access, and can connect us to the resources we might need.

**Comment by hh** [comment]
@BobyMCbobs let's look at using tail scale to handle ingress, that would actually be a good idea regardless of if it's within pair, codespaces, coder, or local. In particular let's explore mapping, public tls DNS to Kubernetes ingresses.

**Comment by BobyMCbobs** [comment]
> @BobyMCbobs let's look at using tail scale to handle ingress, that would actually be a good idea regardless of if it's within pair, codespaces, coder, or local. In particular let's explore mapping, public tls DNS to Kubernetes ingresses.

I believe that Tailscale only does private networks and requires software to use.
